apiVersion: apps/v1
kind: Deployment
metadata:
  name: password-manager
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: password-manager
  template:
    metadata:
      labels:
        app: password-manager
    spec:
      containers:
        - name: password-manager
          image: nidhi8901/web-based-password-manager:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: password-manager-secret
                  key: ENCRYPTION_KEY
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
